name: build_push

on: [push]

jobs:
  run_docker_build:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        distro:
          - image: pdns-recursor
            version: "5.0"
            tags: "5.0"
          - image: pdns-recursor
            version: "5.1"
            tags: "5.1"
          - image: pdns-recursor
            version: "5.2"
            tags: "5.2"
          - image: pdns-recursor
            version: "5.3"
            tags: "5.3,latest"
    uses: hybridadmin/reuse-workflows/.github/workflows/build_push_apps.yml@main
    secrets: inherit
    with:
      distro_image: '${{ matrix.distro.image }}'
      distro_tags: '${{ matrix.distro.tags }}'
      distro_platform: 'linux/amd64,linux/arm64'
      distro_version: '${{ matrix.distro.version }}'
      skip_tests: 'true'

  run_update_readme:
    needs:
      - run_docker_build
    uses: hybridadmin/reuse-workflows/.github/workflows/update_readme.yml@main
    secrets: inherit
    with:
      repo_name: 'hybridadmin/pdns-recursor'
